#!/bin/sh /etc/rc.common

USE_PROCD=1
START=98
STOP=02

DEVICE="/dev/video0"
WIDTH=640
HEIGHT=480
FPS=15
PORT=8888

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/mjpg_streamer \
        -i "input_uvc.so -d $DEVICE -r ${WIDTH}x${HEIGHT} -f $FPS" \
        -o "output_http.so -p $PORT -w /www/mjpg-streamer"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 0
    procd_close_instance
}
